### ISSUE TITLE
s3 connecting to aws bucket

### ISSUE THREAD

**Issue by rjtj2007** [TeressaJohnosnStudio/TJS#20]
commit: 508f51fadde6055150786d018f1940a84b39dda3

I backed up from the multer issue we worked through the other day to an old commit where the button upload on the about page does upload a file (actually two files) to the upload folder.

I am ultimately attempting to get or post images used in our website from an existing aws bucket. I will slack you the bucket info so that you can take a crack at it too.

Thank you.

**Comment by michaeltreat** [comment]
Hey Ryan

So, getting an image from S3 is super easy. When you post an image you are given a url, all you need to do is reach out to that url to get the image. You should store that url in your mongo database.

**Comment by michaeltreat** [comment]
Woohoo!
